name: Collect data every day at 1 a.m and Push Changes

on:
  schedule:
    - cron: '0 1 * * *'  # Schedule to run daily at 1 a.m. UTC
  workflow_dispatch:  # Make the workflow manually runnable

permissions:
  contents: write  # Grant write permissions to the workflow

jobs:
  collect-data-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt


    - name: Run predict_and_trade.py
      run: |
        python predict_and_trade.py

    - name: Commit and Push Signals with AccessToken
      run: |
        git config --global user.name 'ActionBot'
        git config --global user.email 'luca.burghard@web.de'
        git add .
        git commit -m "Buy or Sell Signal calculated and executed."
        git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
        git push
